### ISSUE TITLE
stylis is not defined

### ISSUE THREAD

**Issue by warapitiya** [michaelauderer/stencil-styled-components#3]
When running the app it throws the error "ReferenceError: stylis is not defined"

it uses `stylis`
```js
// parse the rule with stylis and add to our <style> tag
  const rule = stylis('html /deep/ .' + componentId, css);
```
But the defined variable name is:
```js
var stylis_min = createCommonjsModule(function (module, exports) {....});
```

**Comment by dangodev** [comment]
Still getting this error. Maybe the fix hasn’t been published to npm yet?

**Comment by michaelauderer** [comment]
@dangodev Right, it wasn't published yet. I just now published 1.3.4 which includes this!

**Comment by AlrikOlson** [comment]
@auderer 

https://github.com/auderer/stencil-styled-components/commit/53055a0e5bcadbc46e62e8bff47bc90f7e978286#diff-d0a381622d0ae45c96908c5e3dd2c566

This commit reverted the change made to fix this issue.

**Comment by lynellf** [comment]
The error has returned?
